"""
kanban_connector.py
-------------------
Receives a PMBOK-formatted risk JSON payload from the n8n AI Agent and
creates or updates a ticket on Trello (default) or Jira.

Designed to be called by n8n's Execute Command node. The JSON payload
is passed as a command-line argument or via stdin.

Usage:
    # Trello (default)
    python kanban_connector.py --payload '{"risk_id": "RSK-001", ...}'

    # Jira
    python kanban_connector.py --provider jira --payload '{"risk_id": ...}'

    # From stdin (n8n pipe)
    echo '{"risk_id": ...}' | python kanban_connector.py --stdin

Environment variables:
    TRELLO_API_KEY      — Trello developer API key
    TRELLO_TOKEN        — Trello user OAuth token
    TRELLO_BOARD_ID     — Target board ID (from board URL)
    TRELLO_LIST_ID      — Target list ID (the "Risks" column)

    JIRA_BASE_URL       — e.g. https://yourorg.atlassian.net
    JIRA_USER_EMAIL     — Atlassian account email
    JIRA_API_TOKEN      — Atlassian API token
    JIRA_PROJECT_KEY    — e.g. PROJ
"""

import argparse
import json
import logging
import os
import sys
from datetime import datetime, timezone
from typing import Optional

import requests
from dotenv import load_dotenv

load_dotenv()

# ── Logging ───────────────────────────────────────────────────────────────────
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[
        logging.FileHandler("logs/kanban_connector.log"),
        logging.StreamHandler(sys.stderr),
    ],
)
log = logging.getLogger(__name__)


# ── Risk schema (matches risk_register.schema.json) ───────────────────────────
REQUIRED_FIELDS = {"risk_id", "title", "category", "probability", "impact_score", "mitigation"}
VALID_CATEGORIES = {"Technical", "Schedule", "Resource", "Quality", "External"}
VALID_PROBABILITIES = {"Low", "Medium", "High", "Critical"}


def validate_payload(payload: dict) -> list[str]:
    """Returns a list of validation errors (empty = valid)."""
    errors = []
    missing = REQUIRED_FIELDS - payload.keys()
    if missing:
        errors.append(f"Missing required fields: {missing}")

    cat = payload.get("category")
    if cat and cat not in VALID_CATEGORIES:
        errors.append(f"Invalid category '{cat}'. Must be one of {VALID_CATEGORIES}")

    prob = payload.get("probability")
    if prob and prob not in VALID_PROBABILITIES:
        errors.append(f"Invalid probability '{prob}'. Must be one of {VALID_PROBABILITIES}")

    score = payload.get("impact_score")
    if score is not None and not (1 <= int(score) <= 10):
        errors.append(f"impact_score must be 1–10, got {score}")

    return errors


# ── Card content builder (shared between providers) ───────────────────────────
PRIORITY_LABELS = {
    "Critical": "🔴",
    "High":     "🟠",
    "Medium":   "🟡",
    "Low":      "🟢",
}

CATEGORY_EMOJI = {
    "Technical":  "⚙️",
    "Schedule":   "📅",
    "Resource":   "👥",
    "Quality":    "✅",
    "External":   "🌐",
}


def build_card_title(payload: dict) -> str:
    prob = payload.get("probability", "")
    cat  = payload.get("category", "")
    icon = PRIORITY_LABELS.get(prob, "⚪")
    cat_icon = CATEGORY_EMOJI.get(cat, "")
    return f"{icon} [{payload['risk_id']}] {cat_icon} {payload['title']}"


def build_card_description(payload: dict) -> str:
    raised_from = payload.get("raised_from", "N/A")
    status      = payload.get("status", "Open")
    date        = payload.get("date", datetime.now(timezone.utc).strftime("%Y-%m-%d"))
    owner       = payload.get("owner", "Unassigned")

    return (
        f"## 🚨 Risk Detail\n\n"
        f"| Field | Value |\n"
        f"|---|---|\n"
        f"| **Risk ID** | `{payload['risk_id']}` |\n"
        f"| **Category** | {payload.get('category', 'N/A')} |\n"
        f"| **Probability** | {payload.get('probability', 'N/A')} |\n"
        f"| **Impact Score** | {payload.get('impact_score', 'N/A')} / 10 |\n"
        f"| **Status** | {status} |\n"
        f"| **Owner** | {owner} |\n"
        f"| **Raised From** | `{raised_from}` |\n"
        f"| **Date Identified** | {date} |\n\n"
        f"## 🛡️ Mitigation Strategy\n\n"
        f"{payload.get('mitigation', '_No mitigation defined._')}\n\n"
        f"---\n"
        f"_Auto-generated by Agentic PMBOK Toolkit · {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}_"
    )


# ── Trello provider ───────────────────────────────────────────────────────────
class TrelloConnector:
    API_BASE = "https://api.trello.com/1"

    # Map impact score → Trello label color
    IMPACT_LABEL_MAP = {
        range(1, 4):  "green",
        range(4, 7):  "yellow",
        range(7, 9):  "orange",
        range(9, 11): "red",
    }

    def __init__(self) -> None:
        self.api_key  = _require_env("TRELLO_API_KEY")
        self.token    = _require_env("TRELLO_TOKEN")
        self.board_id = _require_env("TRELLO_BOARD_ID")
        self.list_id  = _require_env("TRELLO_LIST_ID")
        self.session  = requests.Session()
        self.session.params = {"key": self.api_key, "token": self.token}  # type: ignore

    def _get(self, path: str, **params) -> dict | list:
        r = self.session.get(f"{self.API_BASE}{path}", params=params, timeout=15)
        r.raise_for_status()
        return r.json()

    def _post(self, path: str, data: dict) -> dict:
        r = self.session.post(f"{self.API_BASE}{path}", json=data, timeout=15)
        r.raise_for_status()
        return r.json()

    def _put(self, path: str, data: dict) -> dict:
        r = self.session.put(f"{self.API_BASE}{path}", json=data, timeout=15)
        r.raise_for_status()
        return r.json()

    def _impact_color(self, score: int) -> str:
        for r, color in self.IMPACT_LABEL_MAP.items():
            if score in r:
                return color
        return "blue"

    def _get_or_create_label(self, name: str, color: str) -> str:
        labels = self._get(f"/boards/{self.board_id}/labels")
        for lb in labels:
            if lb["name"] == name:
                return lb["id"]
        new_label = self._post("/labels", {"name": name, "color": color, "idBoard": self.board_id})
        return new_label["id"]

    def _find_existing_card(self, risk_id: str) -> Optional[str]:
        """Check if a card for this risk_id already exists in the list."""
        cards = self._get(f"/lists/{self.list_id}/cards")
        for card in cards:
            if risk_id in card.get("name", ""):
                return card["id"]
        return None

    def upsert_card(self, payload: dict) -> dict:
        risk_id     = payload["risk_id"]
        title       = build_card_title(payload)
        description = build_card_description(payload)
        impact      = int(payload.get("impact_score", 5))
        color       = self._impact_color(impact)
        label_name  = f"Impact-{impact}"
        label_id    = self._get_or_create_label(label_name, color)

        # Category label
        cat_label_id = self._get_or_create_label(
            payload.get("category", "Technical"), "blue"
        )

        existing_id = self._find_existing_card(risk_id)

        if existing_id:
            result = self._put(
                f"/cards/{existing_id}",
                {"name": title, "desc": description, "idLabels": [label_id, cat_label_id]},
            )
            log.info("Updated existing Trello card %s for %s", existing_id, risk_id)
            action = "updated"
        else:
            result = self._post(
                "/cards",
                {
                    "name": title,
                    "desc": description,
                    "idList": self.list_id,
                    "idLabels": [label_id, cat_label_id],
                    "pos": "top",
                },
            )
            log.info("Created new Trello card %s for %s", result["id"], risk_id)
            action = "created"

        return {"action": action, "provider": "trello", "card_id": result["id"], "url": result.get("shortUrl", "")}


# ── Jira provider ─────────────────────────────────────────────────────────────
class JiraConnector:
    PRIORITY_MAP = {"Low": "Low", "Medium": "Medium", "High": "High", "Critical": "Highest"}

    def __init__(self) -> None:
        self.base_url    = _require_env("JIRA_BASE_URL").rstrip("/")
        self.user_email  = _require_env("JIRA_USER_EMAIL")
        self.api_token   = _require_env("JIRA_API_TOKEN")
        self.project_key = _require_env("JIRA_PROJECT_KEY")
        self.session     = requests.Session()
        self.session.auth = (self.user_email, self.api_token)
        self.session.headers.update({"Content-Type": "application/json", "Accept": "application/json"})

    def _post(self, path: str, data: dict) -> dict:
        r = self.session.post(f"{self.base_url}/rest/api/3{path}", json=data, timeout=15)
        r.raise_for_status()
        return r.json()

    def _get(self, path: str, **params) -> dict:
        r = self.session.get(f"{self.base_url}/rest/api/3{path}", params=params, timeout=15)
        r.raise_for_status()
        return r.json()

    def _find_existing_issue(self, risk_id: str) -> Optional[str]:
        jql = f'project="{self.project_key}" AND summary ~ "{risk_id}" ORDER BY created DESC'
        results = self._get("/search", jql=jql, maxResults=1)
        issues = results.get("issues", [])
        return issues[0]["id"] if issues else None

    def upsert_issue(self, payload: dict) -> dict:
        risk_id  = payload["risk_id"]
        title    = build_card_title(payload)
        desc     = build_card_description(payload)
        priority = self.PRIORITY_MAP.get(payload.get("probability", "Medium"), "Medium")

        # Jira uses Atlassian Document Format (ADF) for descriptions
        adf_desc = {
            "version": 1,
            "type": "doc",
            "content": [
                {"type": "paragraph", "content": [{"type": "text", "text": desc}]}
            ],
        }

        existing_id = self._find_existing_issue(risk_id)
        if existing_id:
            self.session.put(
                f"{self.base_url}/rest/api/3/issue/{existing_id}",
                json={"fields": {"summary": title, "description": adf_desc, "priority": {"name": priority}}},
                timeout=15,
            ).raise_for_status()
            log.info("Updated Jira issue %s for %s", existing_id, risk_id)
            return {"action": "updated", "provider": "jira", "issue_id": existing_id}
        else:
            result = self._post(
                "/issue",
                {
                    "fields": {
                        "project": {"key": self.project_key},
                        "summary": title,
                        "description": adf_desc,
                        "issuetype": {"name": "Risk"},
                        "priority": {"name": priority},
                        "labels": [payload.get("category", "Technical").replace(" ", "_"), "AI-Generated"],
                    }
                },
            )
            log.info("Created Jira issue %s for %s", result["key"], risk_id)
            return {"action": "created", "provider": "jira", "issue_id": result["key"], "url": f"{self.base_url}/browse/{result['key']}"}


# ── Audit log ─────────────────────────────────────────────────────────────────
def append_audit_log(payload: dict, result: dict) -> None:
    entry = {
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "risk_id": payload.get("risk_id"),
        "action": result.get("action"),
        "provider": result.get("provider"),
        "card_id": result.get("card_id") or result.get("issue_id"),
        "url": result.get("url", ""),
    }
    path = "artifacts/kanban_audit.jsonl"
    with open(path, "a", encoding="utf-8") as f:
        f.write(json.dumps(entry) + "\n")
    log.info("Audit log appended: %s", entry)


# ── Helpers ───────────────────────────────────────────────────────────────────
def _require_env(key: str) -> str:
    val = os.getenv(key)
    if not val:
        raise EnvironmentError(f"Required environment variable '{key}' is not set.")
    return val


def load_payload(args: argparse.Namespace) -> dict:
    if args.stdin:
        raw = sys.stdin.read().strip()
    elif args.payload:
        raw = args.payload
    elif args.file:
        with open(args.file, encoding="utf-8") as f:
            raw = f.read()
    else:
        raise ValueError("Provide --payload, --file, or --stdin")
    return json.loads(raw)


# ── CLI entry point ───────────────────────────────────────────────────────────
def main() -> None:
    parser = argparse.ArgumentParser(description="Push PMBOK risk payload to a Kanban board")
    parser.add_argument("--provider", choices=["trello", "jira"], default="trello")
    parser.add_argument("--payload", help="JSON string of the risk payload")
    parser.add_argument("--file", help="Path to a JSON file containing the risk payload")
    parser.add_argument("--stdin", action="store_true", help="Read JSON payload from stdin")
    parser.add_argument("--dry-run", action="store_true", help="Validate and print without creating ticket")
    args = parser.parse_args()

    try:
        payload = load_payload(args)
    except (json.JSONDecodeError, ValueError) as e:
        log.error("Failed to parse payload: %s", e)
        sys.exit(1)

    # Validate schema
    errors = validate_payload(payload)
    if errors:
        log.error("Payload validation failed:\n  " + "\n  ".join(errors))
        print(json.dumps({"success": False, "errors": errors}))
        sys.exit(1)

    if args.dry_run:
        log.info("Dry-run mode — no ticket will be created.")
        print(json.dumps({"success": True, "dry_run": True, "card_title": build_card_title(payload)}, indent=2))
        return

    try:
        if args.provider == "trello":
            connector = TrelloConnector()
            result = connector.upsert_card(payload)
        else:
            connector = JiraConnector()
            result = connector.upsert_issue(payload)

        append_audit_log(payload, result)
        result["success"] = True
        print(json.dumps(result, indent=2))

    except EnvironmentError as e:
        log.error(str(e))
        print(json.dumps({"success": False, "error": str(e)}))
        sys.exit(1)
    except requests.exceptions.HTTPError as e:
        log.error("API error: %s — %s", e.response.status_code, e.response.text[:300])
        print(json.dumps({"success": False, "error": str(e)}))
        sys.exit(1)
    except Exception as e:
        log.exception("Unexpected error: %s", e)
        sys.exit(1)


if __name__ == "__main__":
    main()
