"""
api/main.py
-----------
FastAPI server that exposes the live PMBOK artifact files as REST endpoints.
The React dashboard calls these instead of using hardcoded seed data.

Endpoints:
    GET  /api/risks                 → full risk_register.json
    GET  /api/risks/{risk_id}       → single risk entry
    GET  /api/velocity              → full velocity_log.json
    GET  /api/velocity/{sprint_id}  → single sprint entry
    GET  /api/stakeholders          → stakeholder_map.json
    GET  /api/pipeline/runs         → last N pipeline audit log entries
    GET  /api/pipeline/stats        → aggregated run statistics
    GET  /api/health                → server + artifact health check
    POST /api/pipeline/trigger      → manually trigger an agent pipeline run

Start:
    uvicorn api.main:app --reload --port 8000

    OR via Docker Compose (see docker-compose.yml)
"""

import json
import os
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from dotenv import load_dotenv
from fastapi import FastAPI, HTTPException, BackgroundTasks, Query
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from pydantic import BaseModel

load_dotenv()

# ── Paths ─────────────────────────────────────────────────────────────────────
BASE          = Path(__file__).resolve().parent.parent
ARTIFACTS_DIR = BASE / "artifacts"
LOGS_DIR      = BASE / "logs"
SRC_DIR       = BASE / "src"

# ── App ───────────────────────────────────────────────────────────────────────
app = FastAPI(
    title="Agentic PMBOK Toolkit API",
    description="Serves live PMBOK artifacts generated by the AI Scrum Master agent.",
    version="1.0.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173", "http://localhost:3000", "*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


# ── Helpers ───────────────────────────────────────────────────────────────────
def _load_json(path: Path) -> dict:
    if not path.exists():
        raise HTTPException(status_code=404, detail=f"Artifact not found: {path.name}")
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        raise HTTPException(status_code=500, detail=f"Corrupt artifact file: {e}")


def _load_jsonl(path: Path, limit: int = 50) -> list[dict]:
    if not path.exists():
        return []
    lines = path.read_text(encoding="utf-8").strip().splitlines()
    entries = []
    for line in reversed(lines[-limit:]):
        try:
            entries.append(json.loads(line))
        except json.JSONDecodeError:
            continue
    return entries


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


# ── Health ────────────────────────────────────────────────────────────────────
@app.get("/api/health", tags=["System"])
def health():
    """Check server health and artifact file availability."""
    artifacts = {}
    for name in ["risk_register.json", "velocity_log.json", "stakeholder_map.json"]:
        path = ARTIFACTS_DIR / name
        artifacts[name] = {
            "exists": path.exists(),
            "size_bytes": path.stat().st_size if path.exists() else 0,
            "last_modified": datetime.fromtimestamp(
                path.stat().st_mtime, tz=timezone.utc
            ).isoformat() if path.exists() else None,
        }
    return {
        "status": "ok",
        "timestamp": _now(),
        "artifacts": artifacts,
        "python": sys.version,
    }


# ── Risk Register ─────────────────────────────────────────────────────────────
@app.get("/api/risks", tags=["Risk Register"])
def get_risks(
    status:   Optional[str] = Query(None, description="Filter by status: Open, Mitigating, Resolved"),
    category: Optional[str] = Query(None, description="Filter by category: Technical, Schedule, Resource, Quality, External"),
    min_impact: Optional[int] = Query(None, ge=1, le=10, description="Minimum impact score"),
):
    """Return all risks with optional filters."""
    data = _load_json(ARTIFACTS_DIR / "risk_register.json")
    risks = data.get("risks", [])

    if status:
        risks = [r for r in risks if r.get("status", "").lower() == status.lower()]
    if category:
        risks = [r for r in risks if r.get("category", "").lower() == category.lower()]
    if min_impact is not None:
        risks = [r for r in risks if r.get("impact_score", 0) >= min_impact]

    # Sort by risk_score descending (highest risk first)
    risks = sorted(risks, key=lambda r: r.get("risk_score", 0), reverse=True)

    return {
        "project_id":   data.get("project_id"),
        "last_updated": data.get("last_updated"),
        "total":        len(risks),
        "risks":        risks,
    }


@app.get("/api/risks/summary", tags=["Risk Register"])
def get_risk_summary():
    """Aggregated risk statistics for dashboard KPI cards."""
    data  = _load_json(ARTIFACTS_DIR / "risk_register.json")
    risks = data.get("risks", [])

    by_status   = {}
    by_category = {}
    by_prob     = {}

    for r in risks:
        s = r.get("status", "Unknown")
        c = r.get("category", "Unknown")
        p = r.get("probability", "Unknown")
        by_status[s]   = by_status.get(s, 0) + 1
        by_category[c] = by_category.get(c, 0) + 1
        by_prob[p]     = by_prob.get(p, 0) + 1

    open_risks    = [r for r in risks if r.get("status") in ("Open", "Mitigating")]
    critical      = [r for r in risks if r.get("impact_score", 0) >= 8]
    avg_impact    = round(sum(r.get("impact_score", 0) for r in risks) / len(risks), 1) if risks else 0

    return {
        "total":          len(risks),
        "open":           len(open_risks),
        "critical":       len(critical),
        "avg_impact":     avg_impact,
        "by_status":      by_status,
        "by_category":    by_category,
        "by_probability": by_prob,
        "last_updated":   data.get("last_updated"),
    }


@app.get("/api/risks/{risk_id}", tags=["Risk Register"])
def get_risk(risk_id: str):
    """Return a single risk entry by ID."""
    data  = _load_json(ARTIFACTS_DIR / "risk_register.json")
    risks = data.get("risks", [])
    match = next((r for r in risks if r["risk_id"].upper() == risk_id.upper()), None)
    if not match:
        raise HTTPException(status_code=404, detail=f"Risk '{risk_id}' not found")
    return match


# ── Velocity Log ──────────────────────────────────────────────────────────────
@app.get("/api/velocity", tags=["Velocity"])
def get_velocity():
    """Return full sprint velocity log."""
    data = _load_json(ARTIFACTS_DIR / "velocity_log.json")
    sprints = data.get("sprints", [])

    # Enrich each sprint with computed velocity percentage
    for s in sprints:
        planned   = s.get("metrics", {}).get("story_points_planned", 0)
        completed = s.get("metrics", {}).get("story_points_completed", 0)
        s["velocity_pct"] = round((completed / planned * 100), 1) if planned > 0 else 0

    return {
        "project_id":   data.get("project_id"),
        "last_updated": data.get("last_updated"),
        "sprint_count": len(sprints),
        "sprints":      sprints,
    }


@app.get("/api/velocity/current", tags=["Velocity"])
def get_current_sprint():
    """Return the currently active sprint."""
    data    = _load_json(ARTIFACTS_DIR / "velocity_log.json")
    sprints = data.get("sprints", [])
    active  = next((s for s in sprints if s.get("status") == "Active"), None)
    if not active:
        # Fall back to most recent sprint
        active = sprints[-1] if sprints else None
    if not active:
        raise HTTPException(status_code=404, detail="No active sprint found")

    planned   = active.get("metrics", {}).get("story_points_planned", 0)
    completed = active.get("metrics", {}).get("story_points_completed", 0)
    active["velocity_pct"] = round((completed / planned * 100), 1) if planned > 0 else 0
    return active


@app.get("/api/velocity/{sprint_id}", tags=["Velocity"])
def get_sprint(sprint_id: str):
    """Return a single sprint by ID."""
    data    = _load_json(ARTIFACTS_DIR / "velocity_log.json")
    sprints = data.get("sprints", [])
    match   = next((s for s in sprints if s["sprint_id"].upper() == sprint_id.upper()), None)
    if not match:
        raise HTTPException(status_code=404, detail=f"Sprint '{sprint_id}' not found")
    return match


# ── Stakeholders ──────────────────────────────────────────────────────────────
@app.get("/api/stakeholders", tags=["Stakeholders"])
def get_stakeholders():
    """Return stakeholder map. Returns empty list if file not yet generated."""
    path = ARTIFACTS_DIR / "stakeholder_map.json"
    if not path.exists():
        return {"project_id": None, "stakeholders": [], "last_updated": None}
    data = _load_json(path)
    return data


# ── Pipeline Audit Log ────────────────────────────────────────────────────────
@app.get("/api/pipeline/runs", tags=["Pipeline"])
def get_pipeline_runs(limit: int = Query(50, ge=1, le=500)):
    """Return the last N pipeline audit log entries, newest first."""
    entries = _load_jsonl(LOGS_DIR / "pipeline_audit.jsonl", limit=limit)
    return {
        "total":   len(entries),
        "limit":   limit,
        "runs":    entries,
    }


@app.get("/api/pipeline/stats", tags=["Pipeline"])
def get_pipeline_stats():
    """Aggregated pipeline statistics for dashboard."""
    entries = _load_jsonl(LOGS_DIR / "pipeline_audit.jsonl", limit=500)
    if not entries:
        return {"total_runs": 0, "message": "No pipeline runs recorded yet"}

    total        = len(entries)
    successful   = sum(1 for e in entries if e.get("success"))
    failed       = total - successful
    total_tokens = sum(e.get("input_tokens", 0) + e.get("output_tokens", 0) for e in entries)
    avg_duration = round(sum(e.get("duration_sec", 0) for e in entries) / total, 2)

    by_type = {}
    for e in entries:
        t = e.get("output_type", "UNKNOWN")
        by_type[t] = by_type.get(t, 0) + 1

    by_provider = {}
    for e in entries:
        p = e.get("provider", "unknown")
        by_provider[p] = by_provider.get(p, 0) + 1

    return {
        "total_runs":    total,
        "successful":    successful,
        "failed":        failed,
        "success_rate":  round(successful / total * 100, 1),
        "total_tokens":  total_tokens,
        "avg_duration_sec": avg_duration,
        "by_output_type":  by_type,
        "by_provider":     by_provider,
        "latest_run":      entries[0] if entries else None,
    }


# ── Manual pipeline trigger ───────────────────────────────────────────────────
class TriggerRequest(BaseModel):
    repo:         str
    sprint_id:    str = "SP-03"
    sprint_start: str = "2026-05-12"
    sprint_end:   str = "2026-05-25"
    provider:     Optional[str] = None
    dry_run:      bool = True


def _run_pipeline_background(req: TriggerRequest):
    """Run agent_pipeline.py as a subprocess (non-blocking)."""
    cmd = [
        sys.executable, str(SRC_DIR / "agent_pipeline.py"),
        "--repo",   req.repo,
        "--sprint", req.sprint_id,
        "--start",  req.sprint_start,
        "--end",    req.sprint_end,
        "--output", "json",
    ]
    if req.provider:
        cmd += ["--provider", req.provider]
    if req.dry_run:
        cmd.append("--dry-run")

    try:
        result = subprocess.run(
            cmd, capture_output=True, text=True, timeout=120,
            env={**os.environ},
        )
        log_path = LOGS_DIR / "api_triggers.jsonl"
        entry = {
            "timestamp":   _now(),
            "repo":        req.repo,
            "returncode":  result.returncode,
            "stdout":      result.stdout[:2000],
            "stderr":      result.stderr[:500],
        }
        with open(log_path, "a", encoding="utf-8") as f:
            f.write(json.dumps(entry) + "\n")
    except Exception as e:
        print(f"Background pipeline run failed: {e}")


@app.post("/api/pipeline/trigger", tags=["Pipeline"])
def trigger_pipeline(req: TriggerRequest, background_tasks: BackgroundTasks):
    """
    Manually trigger an agent pipeline run.
    Runs in the background — poll /api/pipeline/runs to see the result.
    """
    if not os.getenv("GITHUB_TOKEN"):
        raise HTTPException(
            status_code=400,
            detail="GITHUB_TOKEN is not set. Cannot trigger pipeline."
        )
    background_tasks.add_task(_run_pipeline_background, req)
    return {
        "status":   "triggered",
        "message":  "Pipeline run started in background. Poll /api/pipeline/runs for results.",
        "dry_run":  req.dry_run,
        "repo":     req.repo,
        "timestamp": _now(),
    }


# ── Dashboard summary (single call for the React app) ────────────────────────
@app.get("/api/dashboard", tags=["Dashboard"])
def get_dashboard():
    """
    Single endpoint that returns everything the React dashboard needs.
    Minimises client-side fetch calls.
    """
    risks_data    = _load_json(ARTIFACTS_DIR / "risk_register.json")
    velocity_data = _load_json(ARTIFACTS_DIR / "velocity_log.json")
    pipeline_runs = _load_jsonl(LOGS_DIR / "pipeline_audit.jsonl", limit=20)

    sprints = velocity_data.get("sprints", [])
    for s in sprints:
        planned   = s.get("metrics", {}).get("story_points_planned", 0)
        completed = s.get("metrics", {}).get("story_points_completed", 0)
        s["velocity_pct"] = round((completed / planned * 100), 1) if planned > 0 else 0

    risks         = risks_data.get("risks", [])
    open_risks    = [r for r in risks if r.get("status") in ("Open", "Mitigating")]
    critical      = [r for r in risks if r.get("impact_score", 0) >= 8]
    active_sprint = next((s for s in sprints if s.get("status") == "Active"), sprints[-1] if sprints else {})

    total_tokens = sum(
        e.get("input_tokens", 0) + e.get("output_tokens", 0) for e in pipeline_runs
    )

    return {
        "meta": {
            "generated_at":   _now(),
            "risks_updated":  risks_data.get("last_updated"),
            "velocity_updated": velocity_data.get("last_updated"),
        },
        "kpis": {
            "open_risks":      len(open_risks),
            "critical_risks":  len(critical),
            "active_blockers": len(active_sprint.get("blockers", [])),
            "sprint_velocity": active_sprint.get("velocity_pct", 0),
            "pipeline_runs":   len(pipeline_runs),
            "total_tokens":    total_tokens,
            "ai_confidence":   active_sprint.get("ai_confidence", 0),
            "current_sprint":  active_sprint.get("sprint_id", "N/A"),
        },
        "risks":         sorted(risks, key=lambda r: r.get("risk_score", 0), reverse=True),
        "sprints":       sprints,
        "pipeline_runs": pipeline_runs,
    }
